version: '3.9'

services:
    application-server:
        build:
            context: ./application_server
            dockerfile: ./Dockerfile
        image: application-server:latest
        depends_on:
            eureka-server:
                condition: service_healthy
        ports:
            - "8100-8120:8081"
        environment:
            - EUREKA_URI=http://eureka-server:8761/eureka
    eureka-server:
        container_name: eureka-server
        build:
            context: ./eureka_server
            dockerfile: ./Dockerfile
        image: eureka-server:latest
        ports:
            - "8761:8761"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8761"]
            interval: 10s
            timeout: 5s
            retries: 5
    routing-server:
        container_name: routing-server
        build:
            context: ./routing_server
            dockerfile: ./Dockerfile
        image: routing-server:latest
        ports:
            - "8080:8080"
        depends_on:
            eureka-server:
                condition: service_healthy
        environment:
            - EUREKA_URI=http://eureka-server:8761/eureka