server:
  port: 8080
spring:
  application:
    name: routing-server
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registerWithEureka: false
    fetchRegistry: true
app:
  serverSelector:
    selectedAlgorithm: roundRobin